###
POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

    {
    "name": "Samuel Guerrero",
    "profession": "Singer",
    "urlImage": "https://i.postimg.cc/8Cc7X7SQ/Kevin.webp",
    "age": 35,
    "nationality": "Australiano",
    "height": "1.74",
    "telephoneNumber": "47-2614-7162",
    "facebook": "Kevin Parker",
    "twitter": "@tameimpala",
    "github": "Kevin Parker"
  }

###
GET http://localhost:8080/api/users HTTP/1.1

###
GET http://localhost:8080/api/users/64825a93f6bf8745d10e66b7 HTTP/1.1

###
PUT http://localhost:8080/api/users/64828647b12e6d5903494d6d HTTP/1.1
Content-Type: application/json

    {
    "name": "Samuel Guerrero",
    "profession": "Ingeniero",
    "urlImage": "https://i.postimg.cc/8Cc7X7SQ/Kevin.webp",
    "age": 24,
    "nationality": "Mexicano",
    "height": "1.65",
    "telephoneNumber": "953-278-5480",
    "facebook": "Samuel Guerrero",
    "twitter": "@itougn",
    "github": "Samuel Guerrero"
  }

###
DELETE http://localhost:8080/api/users/64828647b12e6d5903494d6d HTTP/1.1