###
POST http://localhost:8080/api/invitados HTTP/1.1
Content-Type: application/json

  {
    "id": "58",
    "status": "Entrando",
    "urlImage": "https://i.postimg.cc/vTGVH3mw/MyQRCode58.png",
    "name": "Invitado de Azarel"
  }
































###
GET http://localhost:8080/api/invitados HTTP/1.1

###
GET http://localhost:8080/api/users/64825a93f6bf8745d10e66b7 HTTP/1.1

###
PUT http://localhost:8080/api/users/64828647b12e6d5903494d6d HTTP/1.1
Content-Type: application/json

    {
    "name": "Samuel Guerrero",
    "profession": "Singer",
    "urlImage": "https://i.postimg.cc/8Cc7X7SQ/Kevin.webp",
    "age": 35,
    "nationality": "Australiano",
    "height": "1.74",
    "telephoneNumber": "47-2614-7162",
    "facebook": "Kevin Parker",
    "twitter": "@tameimpala",
    "github": "Kevin Parker"
  }

###
DELETE http://localhost:8080/api/users/64828647b12e6d5903494d6d HTTP/1.1

###
GET https://aled-server.onrender.com/api/users HTTP/1.1

###
POST https://aled-server.onrender.com/api/users HTTP/1.1
Content-Type: application/json

    {
    "name": "Juan Perez",
    "profession": "Ingeniero",
    "urlImage": "https://i.postimg.cc/25nkBqxG/Emma.jpg",
    "age": 23,
    "nationality": "Mexicano",
    "height": "1.68",
    "telephoneNumber": "59-6823-2351",
    "facebook": "Juan Perez",
    "twitter": "@juanitopz",
    "github": "JuanPerez"
  }

###
DELETE https://aled-server.onrender.com/api/users/648771b1456af8df92d25c2e HTTP/1.1

###
PUT https://aled-server.onrender.com/api/users/6482daf9ea9a9602b2d3d6fa HTTP/1.1
Content-Type: application/json

    {
    "name": "Lila Ramani",
    "profession": "Front End Developer",
    "urlImage": "https://i.postimg.cc/Pq1RJDtm/lila.jpg",
    "age": 30,
    "nationality": "Estadounidense",
    "height": "1.79",
    "telephoneNumber": "956-23-2344",
    "facebook": "Lila Ramani",
    "twitter": "@somecrumb",
    "github": "LilRam"
  }
